name: steve-test-snap
title: steve-test-snap-title
base: core18
version: "2.0.0"
summary: The snap I use for testing
description: |
  This is the snap I use for development and testing
grade: stable
confinement: strict
parts:
  my-part:
    plugin: nil
