name: steve-test-snap
title: steve-test-snap-title
base: core24
platforms:
  amd64:
  arm64:
  armhf:
build-base: core22
version: "5.0.4"
summary: The snap I use for testing and development
description: |
  This is the snap I use for development and testing
grade: stable
confinement: strict
parts:
  my-part:
    plugin: nil
architectures:
  - build-on: arm64
    build-for: arm64
